<form action="<?php echo $_SERVER['REQUEST_URI'];?>" method="post">
	<div class="form-group col-md-6">
		<?php
		if($_GET['id'] == 'registration'){
		?>
		<label for="login">Логин(Обязательно для заполнения)</label>
		<input type="text" class="form-control" name="login" id="login">
		<?php 
		if($errors['login_exsist']){
			echo "<span style='color:red;'>{$errors['login_exsist']}</span><br>"; 
		}else{
			echo "<span style='color:red;'>{$errors['login']}</span><br>";
		}
		
		?>

		<label for="pass">Пароль(Обязательно для заполнения)</label>
		<input type="password" class="form-control" name="pass" id="pass">
		<?php echo "<span style='color:red;'>{$errors['pass']}</span><br>"; ?>

		<?php
		}
		?>
		<label for="name">Имя
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->name, ENT_QUOTES);
			}
			if($_GET['id'] == 'registration'){
				echo "(Обязательно для заполнения, не больше 15 символов)";
			}else{
				echo "(Не больше 15 символов)";
			}
			
		?></label>
		<input type="text" class="form-control" name="name" id="name">
		<?php echo "<span style='color:red;'>{$errors['name']}</span><br>"; ?>

		<label for="second_name">Фамилия
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->sname, ENT_QUOTES);
			}
			if($_GET['id'] == 'registration'){
				echo "(Обязательно для заполнения, не больше 15 символов)";
			}else{
				echo "(Не больше 15 символов)";
			}

		?></label>
		<input type="text" class="form-control" name="second_name" id="second_name">
		<?php echo "<span style='color:red;'>{$errors['second_name']}</span><br>"; ?>

		<label for="grup">Номер группы
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->class, ENT_QUOTES);
			}
			if($_GET['id'] == 'registration'){
				echo "(Обязательно для заполнения)";
			}	

		?></label>
		<input type="text" class="form-control" name="class" id="grup">
		<?php echo "<span style='color:red;'>{$errors['class']}</span><br>"; ?>

		<label for="email">Емейл
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->email, ENT_QUOTES);
			}
			if($_GET['id'] == 'registration'){
				echo "(Обязательно для заполнения)";
			}

		?></label>
		<input type="email" class="form-control" name="email" id="email">
		<?php 
		if($errors['email_exsist']){
			echo "<span style='color:red;'>{$errors['email_exsist']}</span><br>";
		}else{
			echo "<span style='color:red;'>{$errors['email']}</span><br>"; 
		}
		?>

		<label for="score">Баллы ЕГЭ
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->score, ENT_QUOTES);
			}

		?>(Не больше 300)</label>
		<input type="text" class="form-control" name="score" id="score">
		<?php echo "<span style='color:red;'>{$errors['score']}</span><br>"; ?>

		<label for="age">Год рождения
		<?php 
			if($_GET['id'] == 'edit_profile'){
				echo ":".htmlspecialchars($editProf[0]->age, ENT_QUOTES);
			}
			if($_GET['id'] == 'registration'){
				echo "(Обязательно для заполнения)";
			}

		?></label>
		<input type="text" class="form-control" name="age" id="age">
		<?php echo "<span style='color:red;'>{$errors['age']}</span><br>"; ?>

	</div>
	<?php
	if($_GET['id'] == 'registration'){
	?>
	<div class="form-check">
 	<?php echo "<span style='color:red;'>{$errors['local']}</span><br>"; ?>
	  <label class="form-check-label">
	    <input class="form-check-input" type="radio" name="local" id="exampleRadios1" value="resident">
	    Местный
	  </label>
	</div>

	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="radio" name="local" id="exampleRadios2" value="foreign">
	    Иногородний
	  </label>
	</div>

	
	<div class="form-check">

	<?php echo "<span style='color:red;'>{$errors['sex']}</span><br>"; ?>
	  <label class="form-check-label">
	    <input class="form-check-input" type="radio" name="sex" id="exampleRadios3" value="male">
	    Мужской
	  </label>
	</div>
	<div class="form-check">
	  <label class="form-check-label">
	    <input class="form-check-input" type="radio" name="sex" id="exampleRadios4" value="female">
	    Женский
	  </label>
	</div>
	<?php
	}
	
	?>
	<button type="submit" class="btn btn-primary">Отправить</button>
</form>