
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Абитуриент</title>
	<link href="css/bootstrap.css" rel="stylesheet">
	<link href="css/style.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
	<div class="row header">
		<div class="col-md-2 refer">
			<h3><a href="<?php echo $_SERVER['PHP_SELF']; ?>">Абитуриент.ру</a></h3>
		</div>
		<div class="col-md-10">
			<ul class="menu">
				<?php
				if($_COOKIE['login'] and $_COOKIE['pass']){

				?>
					<li class="authUser">
						Вы вошли как <span class="user"><?php echo $arr[0]->email; ?></span>
					</li>
					<li style='padding-right:5px;'>
						<a href="?id=edit_profile">
						Редактировать
						</a>
					</li>
				<?php
				}
				if(!($_COOKIE['login'] and $_COOKIE['pass'])){
				?>
					<li>
						<a href="?id=registration">
						Регистрация
						</a>
					</li>
				<?php
				}
				if($_COOKIE['login'] and $_COOKIE['pass']){
				?>
					<li>
						<a href="?id=del_cook">
						Выход
						</a>
					</li>
				<?php
				}else{
				?>
					<li>
						<a href="?id=login">
						Логин
						</a>
					</li>
				<?php
				}
				?>
			</ul>
			<form class="form-inline" style="float:right;padding-top: 10px;" method ="post" action="?id=search">
				  <div class="form-group">
				    <label for="search">Поиск</label>
				    <input type="search" id="search" class="form-control mx-sm-3 form-control-sm" name="search">
				    
				  </div>
				  <button type="submit" class="btn btn-primary">Искать!</button>
				</form>
		</div>

	</div>
</div>