<?php 

if(!$login and !$pass){
?>
<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
	<div class="form-group col-md-6">
		<label for="login">Логин</label>
		<input type="text" class="form-control" name="login" id="login">
		<label for="pass">Пароль</label>
		<input type="password" class="form-control" name="pass" id="pass">

  </div>
	
	<button type="submit" class="btn btn-primary">Войти</button>
</form>
<?php
}elseif(!$hash){
	echo "<p>Вы неправильно ввели данные.</p><a href='?id=login'>Попробовать еще раз</a>";
}elseif($hash){
	
	
?>
<p>Вы вошли как: <?php echo htmlspecialchars($login); ?></p>
<p><a href='http://test1.ru' >Вернуться на главную!</a></p>
<p><a href='?id=edit_profile'>Редактировать профиль</a>
<?php
}
?>