<?php
echo "<div class='pag_num'>";
	if(!$page == 0){
		echo "<a href='?id=".($page-1)."&sort={$_GET['sort']}'>Назад </a>";
	}
	for($i=0; $i<$numOfPages; $i++){
		if($sort){
		echo "<a href='?id={$i}&sort={$_GET['sort']}'>".($i+1)."</a>";
		}else{
			echo "<a href='?id={$i}'>".($i+1)."</a>";
		}
	}
	if(!($page == ($numOfPages-1))){
		echo "<a href='?id=".($page+1)."&sort={$_GET['sort']}'> Вперед</a>";

	}
echo "</div>";

?>