<div class='pag_num'>
<?php
$pagination = new Util();

	if(!($offset == 0)){



	if($_GET['id'] == 'search'){
		if($search){
			echo "<a href='?id=search&search=".$search."&p=".($offset-1)."&sort={$_GET['sort']}'>Назад </a>";
		}else{
			echo "<a href='?id=search&search=".$search1."&p=".($offset-1)."&sort={$_GET['sort']}'>Назад </a>";
		}
		}else{
			$arrPrev = array(
				'p'=> $offset-1,
				'sort'=>$sort
			);
			$namePrev = 'Назад';
			$b = $pagination->generateUrlForPagination($arrPrev, $namePrev);
			echo $b;
		}
	}	
	for($i=0; $i<$pages; $i++){
		if($_GET['id'] == 'search'){

			if($search){
				if($sort){
					echo "<a href='?id=search&search=".$search."&p={$i}&sort={$_GET['sort']}'>".($i+1)."</a>";
				}else{
					echo "<a href='?id=search&search=".$search."&p={$i}'>".($i+1)."</a>";
				}}else{
				if($sort){
					echo "<a href='?id=search&search=".$search1."&p={$i}&sort={$_GET['sort']}'>".($i+1)."</a>";
				}else{
					echo "<a href='?id=search&search=".$search1."&p={$i}'>".($i+1)."</a>";
				}
				}

		}else{
			if($sort){
			echo "<a href='?p={$i}&sort={$_GET['sort']}'>".($i+1)."</a>";
			}else{
				echo "<a href='?p={$i}'>".($i+1)."</a>";
			}
		}
	}
	if(!($offset == ($pages-1))){

		if($_GET['id'] == 'search'){
			if($search){
			echo "<a href='?id=search&search=".$search."&p=".($offset+1)."&sort={$_GET['sort']}'> Вперед</a>";
		}else{
			echo "<a href='?id=search&search=".$search1."&p=".($offset+1)."&sort={$_GET['sort']}'> Вперед</a>";
		}
		}else{
			echo "<a href='?p=".($offset+1)."&sort={$_GET['sort']}'> Вперед</a>";
		}

	}

?>
</div>