<form action="<?php echo $_SERVER['REQUEST_URI'];?>" method="post">
	<div class="form-group col-md-6">

		<label for="name">Имя:<?php echo htmlspecialchars($editProf[0]['name'], ENT_QUOTES); ?>(Не больше 15 символов)</label>
		<input type="text" class="form-control" name="name" id="name">
		<?php echo "<span style='color:red;'>{$errors['name']}</span><br>"; ?>

		<label for="second_name">Фамилия: <?php echo htmlspecialchars($editProf[0]['second_name'], ENT_QUOTES); ?>(Не больше 15 символов)</label>
		<input type="text" class="form-control" name="second_name" id="second_name">
		<?php echo "<span style='color:red;'>{$errors['second_name']}</span><br>"; ?>

		<label for="grup">Номер группы: <?php echo htmlspecialchars($editProf[0]['grup'], ENT_QUOTES); ?></label>
		<input type="text" class="form-control" name="grup" id="grup">

		<label for="email">Емейл: <?php echo htmlspecialchars($editProf[0]['email'], ENT_QUOTES); ?></label>
		<input type="email" class="form-control" name="email" id="email">

		<label for="score">Баллы ЕГЭ: <?php echo htmlspecialchars($editProf[0]['score'], ENT_QUOTES); ?>(Не больше 300)</label>
		<input type="text" class="form-control" name="score" id="score">
		<?php echo "<span style='color:red;'>{$errors['score']}</span><br>"; ?>

		<label for="age">Год рождения: <?php echo htmlspecialchars($editProf[0]['age'], ENT_QUOTES); ?></label>
		<input type="text" class="form-control" name="age" id="age">

  </div>
	<button type="submit" class="btn btn-primary">Редактировать</button>
</form>