<?php 
if($search){
	echo "Найдены запросы по слову \"$search\":<br>"; 
}else{
	echo "Найдены запросы по слову \"$search1\":<br>";
}
?>
<div class="row content">
		<div class="col-md-10 table">
			<table>
				<thead>
					<tr>
						<th><a href="?id=search&search=<?php
						if($search){ 
						echo $search;
						}else{
							echo $search1;
						}
						?>&sort=name">Имя</th>
						<th><a href="?id=search&search=<?php 

						if($search){
							echo $search;
						}else{
							echo $search1;
						}


						?>&sort=second_name">Фамилия</th>
						<th><a href="?id=search&search=<?php
						if($search){
						echo $search;
						}else{
							echo $search1;
						}
						?>&sort=grup">Номер группы</th>
						<th>Число баллов</th>
					</tr>
				</thead>
				<tbody>


				<?php 
				foreach($cells as $cell){
					echo "<tr>";
						echo "<td>{$cell['name']}</td>";
						echo "<td>{$cell['second_name']}</td>";
						echo "<td>{$cell['grup']}</td>";
						echo "<td>{$cell['score']}</td>";
					echo "</tr>";
				}
				?>
				</tbody>
			</table>
		</div>
	</div>